spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always
      data-locations: classpath:dataBase.sql
  datasource:
    url: jdbc:h2:mem:dataBase
    username: sa
    password: password
    driverClassName: org.h2.Driver
